### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by zergylord** [openai/doom-py#9]
The README doesn't explicitly give installation instructions, but installing via the standard pip3 install -e . doesn't produce any errors. However, attempting to import doom_py fails with the following error:

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zergylord/doom-py/doom_py/__init__.py", line 1, in <module>
    from doom_py.vizdoom import *
ImportError: No module named 'doom_py.vizdoom'

I'm guessing I'm simply missing some step in the installation process that installs vizdoom, what should I do?

**Comment by tlbtlbtlb** [comment]
You also have to build it:
```
python setup.py build   # (or python3)
pip install -e .        # (or pip3)
```
TODO: mention that in the README.

**Comment by zergylord** [comment]
I mentioned that I did exactly that and it didn't work... 

> but installing via the standard pip3 install -e . doesn't produce any errors.

**Comment by zergylord** [comment]
Thanks, missed the build step!

**Comment by josephborrego** [comment]
thank you trevor!

**Comment by Neel-Gupta** [comment]
I am on Windows 10 and a rookie. Could anyone pls tell how to build it in Win10 ? I am having the error : 
`Traceback (most recent call last):
  File "C:/Users/neelg/PycharmProjects/Q_learning/venv/Scripts/Code.py", line 3, in <module>
    import vizdoom
ImportError: No module named 'vizdoom'`

**Comment by josephborrego** [comment]
I couldn't get it to work on Windows, I used ubuntu linux
